- name: Execute Commands on Target
  hosts: localhost  # Change this to your actual target group
  become: yes  # Run tasks with elevated privileges (sudo)

  vars:
    input_commands: "{{ input_commands | default([]) }}"

  tasks:
    - name: Run Custom Commands
      command: "{{ item }}"
      register: command_output
      with_items: "{{ input_commands }}"

    - name: Display Command Output
      debug:
        var: item.stdout_lines
      with_items: "{{ command_output.results }}"

# to run this playbook ansible-playbook random_playbook.yml --extra-vars "input_commands=\"['echo Hello', 'uptime', 'df -h']\"" --ask-become-pass
