- hosts: all
  connection: local
  gather_facts: false
  become: yes  # Run the entire playbook with elevated privileges
  tasks:
    - name: Ensure service is in the desired state
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: "{{ desired_state | default('started') }}"
      register: service_result

    - name: Debug service result
      ansible.builtin.debug:
        var: service_result

    - name: Display results
      ansible.builtin.debug:
        msg: "Action: {{ desired_state | default('started') }}, Service Name: {{ service_name }}"
      loop:
        - { result: "{{ service_result }}", required_args: ["name", "state"] }

    - name: Check for missing arguments
      ansible.builtin.fail:
        msg: "Missing required argument(s) for service task: {{ service_name }}"
      when:
        - service_result.failed | default(false)
        - required_args is defined
        - service_result.changed.keys() | difference(required_args) | length > 0
